<?php

namespace App\Model;

class NewsManager extends AbstractManager
{
    public const TABLE = 'news';

    public function select(): array
    {
        $query = 'SELECT * FROM news ORDER BY createdDate DESC';
        $statement = $this->pdo->query($query);
        $news = $statement->fetchAll();
        return $news; // TODO: Change the autogenerated stub
    }

    /**
     * Insert new item in database
     */
    public function insert(array $news): int
    {
        if ($news['category'] === 'Sword Art Online : Fatal Bullet') {
            $gameId = 1;
        } elseif ($news['category'] === 'Basic Math - Fun With Numbers') {
            $gameId = 2;
        } else {
            $gameId = null;
        }
        $statement = $this->pdo->prepare("INSERT INTO " . self::TABLE . " 
        (title, category, detail, gameId, img_url_news) VALUES
         (:title, :category, :detail, :gameId, :img_url_news)");
        $statement->bindValue('title', $news['title'], \PDO::PARAM_STR);
        $statement->bindValue('category', $news['category'], \PDO::PARAM_STR);
        $statement->bindValue('detail', $news['detail'], \PDO::PARAM_STR);
        $statement->bindValue('game_id', $gameId, \PDO::PARAM_INT);
        $statement->bindValue('img_url_news', $news['img_url_news'], \PDO::PARAM_STR);

        $statement->execute();
        return (int)$this->pdo->lastInsertId();
    }
    /**
     * Update item in database
     */
    public function update(array $news): bool
    {
        if ($news['category'] === 'Sword Art Online : Fatal Bullet') {
            $gameId = 1;
        } elseif ($news['category'] === 'Basic Math - Fun With Numbers') {
            $gameId = 2;
        } else {
            $gameId = null;
        }
        $statement = $this->pdo->prepare("UPDATE " . self::TABLE .
            " SET title = :title, category = :category, detail = :detail, 
        gameId = :gameId, img_url_news = :img_url_news WHERE id=:id");
        $statement->bindValue('id', $news['id'], \PDO::PARAM_INT);
        $statement->bindValue('title', $news['title'], \PDO::PARAM_STR);
        $statement->bindValue('category', $news['category'], \PDO::PARAM_STR);
        $statement->bindValue('detail', $news['detail'], \PDO::PARAM_STR);
        $statement->bindValue('gameId', $gameId, \PDO::PARAM_INT);
        $statement->bindValue('img_url_news', $news['img_url_news'], \PDO::PARAM_STR);

        return $statement->execute();
    }
    public function fetchCommentById(int $id)
    {
        $statement = $this->pdo->prepare("SELECT * FROM comments WHERE newsId=:id");
        $statement->bindValue('id', $id, \PDO::PARAM_INT);
        $statement->execute();

        return $statement->fetchAll();
    }
    public function insertComment(array $comment)
    {
        $statement = $this->pdo->prepare("INSERT INTO comments (comment, newsId) VALUES (:comment, :newsId)");
        $statement->bindValue('comment', $comment['comment'], \PDO::PARAM_STR);
        $statement->bindValue('newsId', $comment['newsId'], \PDO::PARAM_INT);
        $statement->execute();
    }

    public function selectById(int $id)
    {
        $statement = $this->pdo->prepare("SELECT * FROM game WHERE id=:id");
        $statement->bindValue('id', $id, \PDO::PARAM_INT);
        $statement->execute();

        return $statement->fetch();
    }

    public function fetchNewsByGameId(int $id)
    {
        $statement = $this->pdo->prepare("SELECT * FROM news WHERE gameId=:id");
        $statement->bindValue('id', $id, \PDO::PARAM_INT);
        $statement->execute();

        return $statement->fetchAll();
    }
}
